### ISSUE TITLE
Move model parameters tables (Tabs 3a, 3b, 4)

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#22]
Is it possible to move, to centralize, or even to hide the "Model Parameters" tables off to the right in Tabs 3a, 3b and 4?  I would be fine with hiding better.

**Comment by quantum-dan** [comment]
Hid them better.  Dropdowns of the sort used seem to need to be linked to a cell, so hiding them is the most straightforward solution (and I don't think any users are going to be poking around in the AK column or further out).
