### ISSUE TITLE
Add suggested flow threshold value (Tab 4)

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#26]
Based on Daniel's experience using DeCal, add a suggested value or rule-of-thumb for defining the Flow Threshold parameter value.  Some example rule-of-thumbs that I envision: 
1/15 * lowest peak flow; 
1/100 of total volume in cubic feet ....

**Comment by quantum-dan** [comment]
Instructions for adjusting added, as I don't have a numerical rule-of-thumb based on my experience.  In the vast majority of cases any low value is fine; in the exceptions, adjustment is based on trial-and-error while staying below the lowest peak flow.
