### ISSUE TITLE
ReRun Buttons in Post processor (Tab 7)

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#32]
Do you use Andy's "ReRun" buttons at the bottom of the post-processor tab?  Are they helpful - or would it be better to just have these buttons link them to the previous tabs in the workflow?

**Comment by quantum-dan** [comment]
They are definitely helpful as is; I use them often, for cases where I appear to have the right range but just got a bad timeseries/set of k values within that range.
