### ISSUE TITLE
Numbers written out in "KC_values..." csv are weird (Tab 7)

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#33]
For some reason: the C*, KS-D, and RMSE statistics written out to the KC_values" csv are wrong.  Do you even use these in your workflow?  Or is this a legacy of Andy's code?

**Comment by quantum-dan** [comment]
I don't use those; I've been doing all of the work in the DeCal spreadsheet.

**Comment by quantum-dan** [comment]
However, it was also easy to fix in case someone does want to use it.
