### ISSUE TITLE
Include .exe files in bundle on github (if possible)

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#36]
The Rscript.exe and SUSTAINOPT.exe (or SUSTAIN.exe) are not currently in the bundle download-able from github.  Just making you aware of this - as we'll have to either include documentation on where to download OR include with the bundle.

**Comment by quantum-dan** [comment]
Once the next round of changes is done I'll be uploading a zipped bundle with all relevant files as a Release.

**Comment by quantum-dan** [comment]
See https://github.com/quantum-dan/DeCal/releases/tag/v20190821.
