### ISSUE TITLE
DeCal Post-Processor reporting k-s test p-value rather than test statistic

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#37]
I _think_ the KS-D value that is show up in the post-process is the p-value of the KS statistical test, rather than the test statistic itself.  I don't think it is worth going back and repopulating all these values for the paper, but we'll want to make sure its correct for the tool we release.

**Comment by quantum-dan** [comment]
This was the case for k-C* but not k.  Fixed.
